name: e_device_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  carousel_slider: ^5.0.0
  provider: ^6.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/Assets/Images/
 
  fonts:
    - family: CustomFont
      fonts:
        - asset:  lib/Assets/Fonts/Sura-Regular.ttf